### ISSUE TITLE
Key is not defined

### ISSUE THREAD

**Issue by okgolove** [prerender/prerender-aws-s3-cache#2]
If I set up S3_PREFIX_KEY, I get this error:

```
2019-03-14T20:21:28.041Z ReferenceError: key is not defined
at Object.requestReceived (/node_modules/prerender-aws-s3-cache/index.js:11:44)
at next (/node_modules/prerender/lib/server.js:333:13)
at next (/node_modules/prerender/lib/server.js:339:5)
at Promise (/node_modules/prerender/lib/server.js:344:3)
at new Promise (<anonymous>)
at Object.server.firePluginEvent (/node_modules/prerender/lib/server.js:303:9)
at Object.server.onRequest (/node_modules/prerender/lib/server.js:193:7)
at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
at next (/node_modules/express/lib/router/route.js:137:13)
at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)

2019-03-14T20:21:31.712Z ReferenceError: key is not defined
at Object.pageLoaded (/node_modules/prerender-aws-s3-cache/index.js:32:44)
at next (/node_modules/prerender/lib/server.js:333:13)
at next (/node_modules/prerender/lib/server.js:339:5)
at Promise (/node_modules/prerender/lib/server.js:344:3)
at new Promise (<anonymous>)
at Object.server.firePluginEvent (/node_modules/prerender/lib/server.js:303:9)
at firePluginEvent.then.then.then.then.then.then.then (/node_modules/prerender/lib/server.js:264:15)
```

**Comment by thoop** [comment]
Whoops! Sorry about that. I just pushed a fix. Can you confirm that fixes the issue?

**Comment by okgolove** [comment]
@thoop now it works properly. Thank you!
But can you update the npm package? I had to install the package from git.
